# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-Kaolabo
version:      v0.0.1
version_from: lib/WebService/Kaolabo.pm
installdirs:  site
requires:
    Data::Average:                 0
    File::Spec:                    0
    HTTP::Request:                 0
    Imager:                        0
    LWP::UserAgent:                0
    Test::More:                    0
    Test::Perl::Critic:            0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
